Moar checking for blacklisted boards

diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -266,14 +266,29 @@ function resource_mark()
 
   case "${status}" in
     (up)
+      if [ -n "${resources_excluded[${board}]}" ] ; then
+        kcpmsg -l warn "resource ${board} was excluded via configuration in ${configuration} thus not honouring this request"
+        echo "!resource-mark fail"
+        return 1
+      fi
+
       if [ "${var_result[resources:${board}:type]}" = "roach" ] ; then
         if ! kcpcmd -k -r -i -s "${board}" watchdog >& /dev/null ; then
           if [ "${state/missing-roaches/}" = "${state}" ] ; then
-            kcpmsg -l error "resource ${board} unresponsive"
+            kcpmsg -l error "roach resource ${board} unresponsive"
             echo "!resource-mark fail network"
             return 1
           fi
           kcpmsg -l warn "roach resource ${board} not responsive but taking it to be ok"
+        fi
+      elif [ "${var_result[resources:${board}:type]}" = "skarab" ] ; then
+        if ! ping -c 1 -w ${grace} "${board}" >& /dev/null ; then
+          if [ "${state/missing-roaches/}" = "${state}" ] ; then
+            kcpmsg -l error "skarab resource ${board} unresponsive"
+            echo "!resource-mark fail network"
+            return 1
+          fi
+          kcpmsg -l warn "skarab resource ${board} not responsive but taking it to be ok"
         fi
       fi
 
