much improved resource validation

diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -17,6 +17,8 @@ declare -A subarray_list
 declare -A resource_set
 # [board]=subarray
 declare -A resource_use
+# [N]=board
+declare -a resource_free
 
 export KATCP_LABEL=cmc-primary
 
@@ -36,45 +38,154 @@ if [ ! -f ${leases} ] ; then
   fi
 fi
 
-# support functions 
+#################################################################################
+# checking functions
 
-function load_roaches()
+function validate_subarray_list()
+{
+  unset valid_list
+  declare -A valid_list
+
+  echo ?group-list 
+  while read cmd group extra ; do 
+    case "${cmd}" in 
+      (\#group-list)
+        valid_list[${group}]=valid
+        ;;
+      (\!group-list)
+        if [ "${group}" != "ok" ] ; then
+          kcpmsg -l error "unable to work out subarray set (status ${group})"
+          return 1
+        fi
+
+        kcpmsg -l debug "found groups ${!valid_list[*]}"
+
+        for array in ${!subarray_list[@]} ; do
+          if [ "${valid_list[${array}]}" != "valid" ] ; then
+            kcpmsg "relasing subarray ${array}"
+            unset subarray_list[${array}]
+          fi
+        done
+
+        return 0
+        ;;
+    esac
+  done
+}
+
+function validate_resource_free()
+{
+  resource_free=()
+
+  for board in ${!resource_set[*]} ; do
+    if [ "${resource_set[${board}]}" = "up" -a -z "${resource_use[${board}]}" ] ; then
+      resource_free+=(${board})
+    fi
+  done
+
+  kcpmsg -l debug "${#resource_free[*]} boards are available for allocation"
+}
+
+function validate_resource_use()
+{
+  result=0
+
+  resource_use=()
+
+  for array in ${!subarray_list[*]} ; do 
+
+    kcpmsg "checking array ${array}"
+
+    for file in ${CORR_DIR}/${array}-* ; do
+      if [ -f ${file} ] ; then
+
+        kcpmsg -l debug "checking config ${file}"
+
+        for board in $(grep '^ *servers_' ${file} | cut -f2 -d= | tr -s , ' ' ) ; do
+
+          if [ -n "${resource_use[${board}]}" ] ; then
+            kcpmsg -l fatal "resource ${board} allocated twice to ${resource_use[${board}]} and ${array}"
+            result=1
+          fi
+
+          if [ -z "${resource_set[${board}]}" ] ; then
+            kcpmsg -l warn "unknown resource ${board} used in array ${array}, ignoring it"
+          else 
+            resource_use[${board}]=${array}
+
+            kcpmsg "confirming that ${board} is used by ${array}"
+
+            if [ "${resource_set[${board}]}" != "up" ] ; then
+              kcpmsg -l warn "resource ${board} allocated to array ${array}, despite not marked up"
+              result=1
+            fi
+          fi
+        done
+      fi
+    done
+  done
+
+  return ${result}
+}
+
+
+function validate_resource_set()
 {
   unset tmp_set
   declare -A tmp_set
+
+  # policy decision: we only ping very new or very stale boards, 
+  # real monitoring needs to be done elsewhere, in any event 
+  # we should never transition from standby->up automatically
+  # (other than startup) as this may make board replacement problematic
 
   for board in $(grep roach ${leases} | cut -f4 -d ' ') ; do
 
     tmp_set[$board]=standby
 
-    if [ -z  "${resource_set[${board}]}" ] ; then
-      resource_set[$board]=standby
+    if [ -z "${resource_set[${board}]}" ] ; then
+      if ping -W 2 -n -q -c 1 $1 >& /dev/null ; then
+        resource_set[$board]=up
+      else 
+        resource_set[$board]=standby
+      fi
+      # TODO: launch the matching sensor monitor
     fi
 
   done
 
+  # if old board, not in dhcp. not used, marked standby and unpingable, forget it
+
   for board in ${!resource_set[*]} ; do
     if [ -z "${tmp_set[${board}]}" ] ; then
-      unset resource_set[$board]
+      if [ -z "${resource_use[${board}]}" ] ; then
+        if [ "${resource_set[${board}]}" = "standby" ] ; then
+          if ! ping -W 2 -n -q -c 1 $1 >& /dev/null ; then
+            if [ "${state}" = "production" ] ; then
+              kcpmsg -l warn "dropping resource ${board} as unreachable, unregistered, unused and inactive"
+              unset resource_set[$board]
+              # TODO: stop the matching sensor monitor
+            fi 
+          fi 
+        fi
+      fi
     fi
   done
 }
 
-function static_checks()
+function validate_instruments()
 {
-
-  # Resource hardcoded currently, in future:
-  # TODO: work out what roaches we have, maybe from hosts
-  #resource_set=([R0]=standby [R1]=standby [R2]=standby [R3]=standby)
-
-  load_roaches
+  # TODO: split into validate*size and validata*stream ? 
 
   # instrument parameters hardcoded, work out from template in future
+
   instruments_sizes[rts]=2
   instruments_streams[rts]="X:Y"
 
   for instrument in ${instruments_deployed[*]} ; do
     template=${CORR_TEMPLATE}/${instrument}
+
+    # cat $template  | tr '[,=' '\n' | grep ROACH[0-9] | sort -n | tail -1
 
     # TODO: calculate boards required from template, put it size
     # TODO: work out the data stream names, put it in streams
@@ -83,46 +194,8 @@ function static_checks()
 
 }
 
-function dynamic_checks()
-{
-  result=0
-
-  unset resource_use
-
-# TODO: more checking could be done, in particular retrieve list of active groups
-
-  for array in ${subarray_list[*]} ; do 
-    for file in ${CORR_DIR}/${array}-* ; do
-      if [ -f ${file} ] ; then
-        for board in $(grep '^ *servers_' $file | cut -f2 -d= | tr -s , ' ' ) ; do
-          # TODO: check if it is in resources
-
-          if [ -n "${resource_use[${board}]}" ] ; then
-            kcpmsg -l fatal "resource ${board} allocated twice to ${resource_use[${board}]} and ${array}"
-            result=1
-          fi
-
-          resource_use+=([${board}]=${array})
-
-          if [ -z "${resource_set[${board}]}" ] ; then
-            kcpmsg -l warn "unknown resource ${board} used in array ${array}"
-            resource_set+=([${board}]="up"):
-          fi
-
-          if [ "${resource_set[${board}]}" != "up" ] ; then
-            kcpmsg -l warn "resource ${board} allocated to array ${array} despite not marked up"
-            result=1
-            resource_set[${board}]="up"
-          fi
-
-        done
-      else
-        kcpmsg -l warn "no corr config ${file} for ${array} found"
-      fi
-    done
-  done
-
-}
+#################################################################################
+# misc
 
 function lk_get_result()
 {
@@ -151,7 +224,8 @@ function lk_get_result()
 
 }
 
-# primary functions
+#################################################################################
+# primary requests 
 
 function array_list()
 {
@@ -190,6 +264,8 @@ function array_assign()
     return
   fi
 
+  validate_subarray_list
+
   key=$1
 
   # TODO: should query the running listeners 
@@ -198,6 +274,18 @@ function array_assign()
     echo "!array-assign fail"
     return
   fi
+
+  for file in ${CORR_DIR}/${key}-* ; do
+    if [ -f ${file} ] ; then
+      if rm ${file} ; then
+        kcpmsg -l debug "removing old config ${file}"
+      else 
+        kcpmsg -l error "unable to remove old config file ${file}"
+        echo "!array-assign fail"
+        return
+      fi
+    fi
+  done
 
   shift
 
@@ -209,10 +297,10 @@ function array_assign()
 
   if [ "${key}" = "rts" ] ; then
     port=${rts_port}
-    kcpmsg -l info "using hardcoded port ${port} for rts array"
+    kcpmsg "using hardcoded port ${port} for rts array"
   else
     port=0
-    kcpmsg -l info "will select a free port for array other than rts"
+    kcpmsg "will select a free port for array other than rts"
   fi
 
   echo "?listener-create ${key} ${port} 0.0.0.0"
@@ -250,13 +338,15 @@ function array_halt()
   key=$1
 
   if [ -z "${key}" ] ; then
-    kcpmsg "need a subarray to destroy"
+    kcpmsg -l error "need a subarray to destroy"
     echo "!array-halt fail"
     return
   fi
 
+  validate_subarray_list
+
   if [ -z "${subarray_list[$key]}" ] ; then
-    kcpmsg "no state available for array ${key}"
+    kcpmsg -l error "no state available for array ${key}"
     echo "!array-halt fail unknown-array"
     return
   fi
@@ -280,12 +370,14 @@ function resource_list()
 {
   shift
 
-  # TODO: invoke dynamic_checks
+  validate_subarray_list
+  validate_resource_set
+  validate_resource_use
 
   if [ -n "$1" ] ; then
 
     if [ -z "${resource_set[$1]}" ] ; then
-      kcpmsg "resource $1 not found"
+      kcpmsg -l error "resource $1 not found"
       echo "!resource-list fail"
       return 1
     fi
@@ -298,9 +390,9 @@ function resource_list()
       echo "#resource-list ${board} ${resource_set[${board}]} ${resource_use[${board}]}"
     done
 
-    echo "!resource-list ok"
-
   fi
+
+  echo "!resource-list ok"
 }
 
 function resource_mark()
@@ -308,13 +400,13 @@ function resource_mark()
   shift
 
   if [ "$#" -lt 2 ] ; then
-    kcpmsg "insufficient arguments"
+    kcpmsg -l error "insufficient arguments"
     echo "!resource-mark fail"
     return 1
   fi
 
   if [ -z "${resource_set[$1]}" ] ; then
-    kcpmsg "unknown resource ${1}"
+    kcpmsg -l error "unknown resource ${1}"
     echo "!resource-mark fail"
     return
   fi
@@ -337,14 +429,14 @@ function resource_mark()
       ;;
     (standby) 
       if [ -n "${resource_use[$1]}" ] ; then
-        kcpmsg "refusing to release resource $1 held by array ${resource_use[$1]}"
+        kcpmsg -l error "refusing to release resource $1 held by array ${resource_use[$1]}"
         echo "!resource-mark fail"
         return
       fi
       resource_set[$1]="standby"
       ;;
     (*) 
-      kcpmsg "unknown marking ${2} for resource ${1}"
+      kcpmsg -l error "unknown marking ${2} for resource ${1}"
       echo "!resource-mark fail"
       return 1
       ;;
@@ -353,6 +445,7 @@ function resource_mark()
   echo "!resource-mark ok"
 }
 
+#################################################################################
 # subordinate requests
 
 function instrument_list()
@@ -372,7 +465,7 @@ function instrument_probe()
   shift
 
   if [ "$#" -lt 1 ] ; then
-    kcpmsg "insufficient arguments"
+    kcpmsg -l error "insufficient arguments"
     echo "!instrument-probe fail"
     return
   fi
@@ -382,25 +475,20 @@ function instrument_probe()
   need=${instruments_sizes[${instrument}]}
 
   if [ -z "${need}" ]  ; then
-    kcpmsg "no information about instrument ${instrument} found"
+    kcpmsg -l error "no information about instrument ${instrument} found"
     echo "!instrument-probe fail"
     return
   fi
 
-  unset resource_free
-  declare -a resource_free
+  validate_subarray_list
+  validate_resource_set
+  validate_resource_use
+  validate_resource_free
 
-  for board in ${!resource_set[*]} ; do
-    if [ "${resource_set[${board}]}" = "up" -a -z "${resource_use[${board}]}" ] ; then
-      resource_free+=(${board})
-    fi
-  done
-
-  echo ${resource_free[*]}
   have=${#resource_free[*]}
 
   if [ "${have}" -lt "${need}" ] ; then
-    kcpmsg "would need ${need} boards but only have ${have}"
+    kcpmsg -l warn "would need ${need} boards but only have ${have}"
     echo "!instrument-probe ok oversubscribed"
     return
   fi
@@ -415,22 +503,26 @@ function instrument_activate()
   shift
 
   if [ "$#" -lt 2 ] ; then
-    kcpmsg "insufficient arguments (special case)"
+    kcpmsg -l error "insufficient arguments (special case)"
     echo "!instrument-activate fail"
     return
   fi
 
   subarray=$1
-
   instrument=$2
 
   need=${instruments_sizes[${instrument}]}
 
   if [ -z "${need}" ]  ; then
-    kcpmsg "no information about instrument ${instrument} found"
+    kcpmsg -l error "no information about instrument ${instrument} found"
     echo "!instrument-activate fail"
     return
   fi
+
+  validate_subarray_list
+  validate_resource_set
+  validate_resource_use
+  validate_resource_free
 
   if [ -z "${subarray_list[${subarray}]}" ] ; then
     kcpmsg -l error "subarray ${subarray} does not seem to exist"
@@ -438,20 +530,10 @@ function instrument_activate()
     return
   fi
 
-  unset resource_free
-  declare -a resource_free
-
-  for board in ${!resource_set[*]} ; do
-    if [ "${resource_set[${board}]}" = "up" -a -z "${resource_use[${board}]}" ] ; then
-      resource_free+=(${board})
-    fi
-  done
-
-  #echo ${resource_free[*]}
   have=${#resource_free[*]}
 
   if [ "${have}" -lt "${need}" ] ; then
-    kcpmsg "would need ${need} boards but only have ${have}"
+    kcpmsg -l warn "would need ${need} boards but only have ${have}"
     echo "!instrument-activate ok oversubscribed"
     return 1
   fi
@@ -471,7 +553,7 @@ function instrument_activate()
   kcpmsg "about to configure instrument ${instrument} for ${subarray} with ${resource_grab[*]} resources and inputs ${compound/-/ }"
   
   if ! cmc-config ${subarray} ${instrument} ${compound/-/ } ${resource_grab[*]} ; then
-    kcpmsg "unable to generate config for instrument ${instrument} in subarray ${subarray}"
+    kcpmsg -l error "unable to generate config for instrument ${instrument} in subarray ${subarray}"
     echo "!instrument-activate fail"
     return 1
   fi
@@ -486,30 +568,35 @@ function instrument_activate()
     return 1
   fi
 
-  sleep 0.5
+  sleep 1
 
   echo "?client-connect localhost:${nextport} ${subarray}"
   if ! lk_get_result client-connect ; then
     echo "!instrument-activate fail"
+    # TODO: kill the corr instance to release resources
     return 1
   fi
 
   echo "?client-rename corr localhost:${nextport}" 
   if ! lk_get_result client-rename ; then
+    # TODO: kill the corr instance to release resources
     echo "!instrument-activate fail"
     return 1
   fi
 
   for board in ${resource_grab[*]} ; do
+    kcpmsg "assigning resource ${board} to ${subarray}"
     resource_use[${board}]=${subarray}
   done
 
   echo "!instrument-activate ok"
 }
 
+#################################################################################
 # mainloop
 
-static_checks
+validate_instruments
+validate_resource_set
 
 while read line ; do 
 
@@ -556,7 +643,7 @@ while read line ; do
       ;;
     (*)
       if [ "${cmd:0:1}" = '?' ] ; then
-        kcpmsg "cmc primary got unsupported request ${cmd}"
+        kcpmsg -l warn "cmc primary got unsupported request ${cmd}"
         echo "!${cmd:1} fail"
       fi
       ;;
