Attempt at new instrument-list command

diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -295,6 +295,114 @@ function fetch_var()
   done
 }
 
+### support functions ###################################
+
+# instrument-size:name           - how many inputs does it need
+# instrument-input:name          - what input product does it require
+# instrument-outputs:name:#N     - what output products does it generate
+# instrument-resources:name:type - how many boards of what type do we need
+
+push_failure
+
+send_request   var-declare  "instrument-size*"       map
+retrieve_reply var-declare
+send_request   var-declare  "instrument-input*"      map
+retrieve_reply var-declare
+send_request   var-declare  "instrument-outputs*"    map
+retrieve_reply var-declare
+send_request   var-declare  "instrument-resources*"  map
+retrieve_reply var-declare
+
+if ! pop_failure  ; then
+  kcpmsg -l fatal "unable to declare essential instrument tracking state"
+fi
+
+function setup_instruments()
+{
+  local size instrument template geometry art count top available product i required input
+
+  if [ "${#instruments_deployed[@]}" -le 0 ] ; then
+    kcpmsg -l fatal "no instruments deployed"
+    return 1
+  fi
+
+  push_failure
+
+  available=0
+  for instrument in ${instruments_deployed[*]} ; do
+    template=${CORR_TEMPLATE}/${instrument}
+
+    kcpmsg -l debug "checking templates for instrument ${instrument}"
+
+    if [ -f ${template} ] ; then
+
+      size=$(ike -o -k source_mcast_ips ${template} | tr -s ',' '\n' | wc -l)
+      input=$(ike -o -k source_products ${template})
+
+      if [ "${size}" -gt 0 -a -n "${input}" ] ; then
+
+        kcpmsg "instrument ${instrument} uses ${size} inputs"
+
+        send_request   var-declare instrument-outputs   array  ":${instrument}"
+        retrieve_reply var-declare
+
+        send_request   var-declare instrument-resources map    ":${instrument}"
+        retrieve_reply var-declare
+
+        send_request   var-set     instrument-size   "${size}"  string  ":${instrument}"
+        retrieve_reply var-set
+
+        send_request   var-set     instrument-input  "${input}" string  ":${instrument}"
+        retrieve_reply var-set
+
+        i=0
+        for product in $(ike -o -k output_products ${template}) ; do
+          send_request   var-set products "${product}" string ":${instrument}#${i}"
+          retrieve_reply var-set
+          i=$[i+1]
+        done
+
+        if [ "${i}" -le 0 ] ; then
+          kcpmsg -l error "no data products discoverable in instrument ${instrument}"
+          set_failure
+        fi
+
+        required=0
+        for art in ${resource_types[*]} ; do
+
+# could make it search for upper case only ... 
+          required=$(ike -o -k hosts ${template} | tr -s , '\n' | sort -u | grep -ic ${art})
+
+          kcpmsg "instrument ${instrument} requires ${required} ${art} resources"
+
+          send_request   var-set requires "${required}" string ":${instrument}:${art}"
+          retrieve_reply var-set
+        done
+
+        if [ "${required}" -le 0 ] ; then
+          if [ "${state/missing-roaches/}" = "${state}" ] ; then
+            kcpmsg -l fatal "unable to determine resource needs for instrument ${instrument}"
+            set_failure
+          fi
+        fi
+      else
+        kcpmsg -l error "unable to establish what and how many inputs ${instrument} requires"
+        set_failure
+      fi
+
+    else
+      kcpmsg -l fatal "no template available for instrument ${instrument}"
+    fi
+
+  done
+
+  if ! pop_failure ; then
+    kcpmsg -l error "unable to determine instrument layouts"
+    return 1
+  fi
+
+  return 0
+}
 
 ### support functions ###################################
 
@@ -311,7 +419,6 @@ retrieve_reply var-declare
 
 if ! pop_failure  ; then
   kcpmsg -l fatal "unable to declare essential resource tracking state"
-  exit 1
 fi
 
 function check_resources()
@@ -491,6 +598,17 @@ function group_destroyed()
   if ! pop_failure  ; then
     kcpmsg -l error "unable to free all resources held by ${subarray}"
   fi
+}
+
+### api functions ### instrument ########################
+
+function instrument_list()
+{
+  if ! setup_instruments ; then
+    echo "!instrument-list fail"
+  fi
+
+  echo "!instrument-list ok"
 }
 
 ### api functions ### resources #########################
