Subscribe to sensor_servlet sensors after all

diff --git a/cmc/cmc-monitor b/cmc/cmc-monitor
--- a/cmc/cmc-monitor
+++ b/cmc/cmc-monitor
@@ -113,18 +113,18 @@ function activate_servlet_sensors()
     return 1
   fi
 
-#   push_failure
-# 
-# # risky, we assume inform_result isn't clobbered
-#   for key in "${!inform_result[@]}" ; do
-#     send_request relay "${remote}" relay "${remote}" sensor-sampling "${key}" "auto"
-#     retrieve_inform relay
-#   done
-# 
-#   if ! pop_failure ; then
-#     kcpmsg -l warn "unable to subscribe to sensors of ${remote}"
-#     return 1
-#   fi
+  push_failure
+
+# risky, we assume inform_result isn't clobbered
+  for key in "${!inform_result[@]}" ; do
+    send_request relay "${remote}" relay "${remote}" sensor-sampling "${key}" "auto"
+    retrieve_inform relay
+  done
+
+  if ! pop_failure ; then
+    kcpmsg -l warn "unable to subscribe to sensors of ${remote}"
+    return 1
+  fi
 
   return 0
 }
