corr interfacing

diff --git a/cmc/cmc-config b/cmc/cmc-config
--- a/cmc/cmc-config
+++ b/cmc/cmc-config
@@ -3,6 +3,8 @@
 declare -a input_vector
 declare -a resource_set
 
+export KATCP_LABEL=cmc-config
+
 if [ -n "${CMC_CONFIG}" ] ; then
   source "${CMC_CONFIG}"
 else
@@ -31,7 +33,8 @@ while [ -n "$1" ] ; do
   shift
 done
 
-file=${CORR_DIR}/${array}
+name=${array}-${instrument}
+file=${CORR_DIR}/${name}
 template=${CORR_TEMPLATE}/${instrument}
 
 kcpmsg -l debug "intending to build ${file} using ${template}"
@@ -39,12 +42,12 @@ kcpmsg -l debug "have been given resources ${resource_set[*]}"
 kcpmsg -l debug "need to use inputs ${input_vector[*]}"
 
 if [ ! -f ${template} ] ; then
-  kcpmsg "unable to locate template ${template}"
-# exit 1
+  kcpmsg -l error "unable to locate template ${template}"
+  exit 1
 fi
 
 if [ -f ${file} ] ; then
-  kcpmsg "removing previous config ${file}"
+  kcpmsg "removing previous config ${name}"
   rm -f ${file}
 fi
 
@@ -61,6 +64,4 @@ for input in ${input_vector[*]} ; do
 done
 cat ${template} ) | gcc -E - > ${file}
 
-# launch corr 
-
-# unclear - have some way of connecting to it ... 
+kcpmsg "generated config ${name}"
diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -209,8 +209,10 @@ function array_assign()
 
   if [ "${key}" = "rts" ] ; then
     port=${rts_port}
+    kcpmsg -l info "using hardcoded port ${port} for rts array"
   else
     port=0
+    kcpmsg -l info "will select a free port for array other than rts"
   fi
 
   echo "?listener-create ${key} ${port} 0.0.0.0"
@@ -466,10 +468,32 @@ function instrument_activate()
 
   compound=${subarray_list[$subarray]}
 
-  kcpmsg "about to launch instrument ${instrument} for ${subarray} with ${resource_grab[*]} resources and inputs ${compound/-/ }"
+  kcpmsg "about to configure instrument ${instrument} for ${subarray} with ${resource_grab[*]} resources and inputs ${compound/-/ }"
   
-  if ! cmc-instrument ${subarray} ${instrument} ${compound/-/ } ${resource_grab[*]} ; then
-    kcpmsg "unable to launch instrument"
+  if ! cmc-config ${subarray} ${instrument} ${compound/-/ } ${resource_grab[*]} ; then
+    kcpmsg "unable to generate config for instrument ${instrument} in subarray ${subarray}"
+    echo "!instrument-activate fail"
+    return 1
+  fi
+
+  nextport=$(seq ${corr_base} ${corr_end} | grep -E -v -w $(netstat -tan | tr -s ' ' | grep '^tcp '  | cut -f4 -d ' '  | cut -f2 -d: | sort -nu | tr '\n' '|')0 | head -1)
+
+  kcpmsg "selecting port ${nextport} for instrument ${instrument} of array ${subarray}"
+
+  echo "?client-exec ${subarray}-${instrument} ${subarray} network-cmc-corr-stub" ${CORR_DIR}/${subarray}-${instrument} ${nextport}
+  if ! lk_get_result client-exec ; then
+    echo "!instrument-activate fail"
+    return 1
+  fi
+
+  echo "?client-connect localhost:${nextport} ${subarray}"
+  if ! lk_get_result client-exec ; then
+    echo "!instrument-activate fail"
+    return 1
+  fi
+
+  echo "?client-rename corr localhost:${nextport}" 
+  if ! lk_get_result client-rename ; then
     echo "!instrument-activate fail"
     return 1
   fi
