Better quoting

diff --git a/cmc/cmc-hardware b/cmc/cmc-hardware
--- a/cmc/cmc-hardware
+++ b/cmc/cmc-hardware
@@ -102,11 +102,16 @@ function launch_skarab()
 
   push_failure
 
-  send_request   client-exec "monitor-${skarab}" hardware kcprun -s ${skarab} -e error -o info corr2_hardware_sensor_servlet.py -p "${port} --host ${skarab}"
+  send_request   client-exec "monitor-${skarab}" hardware kcprun -s ${skarab} -e error -o info corr2_hardware_sensor_servlet.py -p "${port}" --host "${skarab}"
   retrieve_reply client-exec
 
   send_request   client-config client "monitor-${skarab}"
   retrieve_reply client-config
+
+  if ! pop_failure ; then
+    kcpmsg -l error "unable to start hardware monitor servlet for skarab ${skarab}"
+    return 1
+  fi
 
   now=$(date +%s)
   timeout=$[now+120]
