First step at launching sensor servlet

diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -820,6 +820,21 @@ function instrument_activate()
 
   make_instrument_sensors ${subarray} ${instrument}
 
+  if [ "${state/no-sensors/}" = "${state}" ] ; then
+    extraport=$(seq ${corr_base} ${corr_end} | grep -E -v -w $(netstat -tan | tr -s ' ' | grep '^tcp '  | cut -f4 -d ' '  | cut -f2 -d: | sort -nu | tr '\n' '|')0 | head -1)
+
+    kcpmsg "selecting ${extraport} for sensor"
+
+    echo "?client-exec ${subarray}-${instrument}-sensors ${subarray} kcprun corr2_sensor_servlet.py -p ${extraport}"
+
+    if ! get_katcp_reply client-exec ; then
+      kcpmsg -l warn "unable to launch sensors for instrument ${instrument} in ${subarray} but going on anyway"
+    fi
+
+  else
+    kcpmsg -l warn "sensor servlet inhibited by configuration"
+  fi
+
   echo "!instrument-activate ok"
 }
 
