Try to establish subarray port

diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -229,10 +229,10 @@ function validate_instruments()
 #################################################################################
 # misc
 
-function lk_get_result()
+function get_katcp_reply()
 {
-  as=$2
   get=$1
+  as=$2
 
   while read cmd code extra ; do 
     case "${cmd}" in 
@@ -251,6 +251,50 @@ function lk_get_result()
           return 1
         fi
         ;;
+      (\!*)
+        kcpmsg -l warn "discarding unexpected response ${cmd}"
+        ;;
+      (\?*)
+        kcpmsg -l fatal "rejecting untimely request ${cmd}, still busy servicing ${get}"
+        echo "!${cmd:1} fail"
+        ;;
+
+    esac
+  done
+
+}
+
+function get_katcp_inform()
+{
+  get=$1
+  match=$2
+
+  while read cmd code extra ; do 
+    case "${cmd}" in 
+      (\#${get})
+        if [ -n "${match}" ] ; then 
+          if [ "${match}" = "${code}" ] ; then
+            result=${extra}
+          fi
+        else 
+          result=${extra}
+        fi
+        ;;
+      (\!${get})
+        if [ "${code}" = "ok" ] ; then
+          return 0
+        else
+          return 1
+        fi
+        ;;
+      (\!*)
+        kcpmsg -l warn "discarding unexpected response ${cmd}"
+        ;;
+      (\?*)
+        kcpmsg -l fatal "rejecting untimely request ${cmd}, still busy servicing ${get}"
+        echo "!${cmd:1} fail"
+        ;;
+
     esac
   done
 
@@ -259,26 +303,26 @@ function lk_get_result()
 function make_subarray_sensors()
 {
   echo "?var-declare ${1}*device-status* sensor,map"
-  lk_get_result var-declare
+  get_katcp_reply var-declare
 
   echo "?var-set ${1}*device-status* ok string :value"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1}*device-status* ${1:-system}\_health string :help"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1}*device-status* nominal string :status"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1}*device-status* discrete string :type"
-  lk_get_result var-set
+  get_katcp_reply var-set
 
   echo "?var-set ${1}*device-status* ok       string :range#0"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1}*device-status* degraded string :range#1"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1}*device-status* fail     string :range#2"
-  lk_get_result var-set
+  get_katcp_reply var-set
 
   echo "?broadcast ${1} interface-changed sensor-list"
-  lk_get_result broadcast
+  get_katcp_reply broadcast
 }
 
 # name, help, type, units, value, status
@@ -286,19 +330,19 @@ function make_subarray_sensors()
 function make_plain_sensor()
 {
   echo "?var-declare ${1} sensor,map"
-  lk_get_result var-declare
+  get_katcp_reply var-declare
 
   echo "?var-set ${1} ${2// /\\_} string :help"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1} ${3} string :type"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1} ${4} string :units"
-  lk_get_result var-set
+  get_katcp_reply var-set
 
   echo "?var-set ${1} ${5} string :value"
-  lk_get_result var-set
+  get_katcp_reply var-set
   echo "?var-set ${1} ${6} string :status"
-  lk_get_result var-set
+  get_katcp_reply var-set
 
 }
 
@@ -335,7 +379,7 @@ function make_instrument_sensors()
   make_plain_sensor "${1}*synchronisation-epoch*"      "last synchronisation time"       integer seconds 0 unknown
 
   echo "?broadcast ${1} interface-changed sensor-list"
-  lk_get_result broadcast
+  get_katcp_reply broadcast
 }
 
 #################################################################################
@@ -421,7 +465,7 @@ function array_assign()
   kcpmsg -l info "have ${match} instruments on offer for a subarray of $# inputs"
 
   echo "?group-create $key"
-  if ! lk_get_result group-create ; then
+  if ! get_katcp_reply group-create ; then
     echo "!array-assign fail"
     return
   fi
@@ -435,16 +479,32 @@ function array_assign()
   fi
 
   echo "?listener-create ${key} ${port} 0.0.0.0"
-  if ! lk_get_result listener-create ; then
+  if ! get_katcp_reply listener-create ; then
     echo "?group-halt ${key}"
     echo "!array-assign fail"
     return
   fi
 
 # TODO - retrieve port number for return code
+  if [ "$port" -le "0" ] ; then
+    echo "?listener-list ${key}" 
+    result=0
+    if ! get_katcp_inform listener-list ${key} ; then
+      echo "?group-halt ${key}"
+      echo "!array-assign fail"
+      return
+    fi
+    if [ "${result}" -le "0" ] ; then
+      kcpmsg -l error "unable to determine port for ${key}"
+      echo "?group-halt ${key}"
+      echo "!array-assign fail"
+      return
+    fi
+    port=${result}
+  fi 
 
   echo "?client-exec subordinate ${key} cmc-subordinate ${key} $*"
-  if ! lk_get_result client-exec ; then
+  if ! get_katcp_reply client-exec ; then
     echo "?group-halt ${key}"
     echo "!array-assign fail"
     return
@@ -496,7 +556,7 @@ function array_halt()
 
   echo "?group-halt ${key}"
 
-  lk_get_result group-halt array-halt
+  get_katcp_reply group-halt array-halt
 }
 
 function resource_list()
@@ -700,7 +760,7 @@ function instrument_activate()
 
 #echo "?client-exec ${subarray}-${instrument} ${subarray} network-cmc-corr-stub" ${CORR_DIR}/${subarray}-${instrument} ${nextport}
   echo "?client-exec ${subarray}-${instrument} ${subarray} kcprun corr2_servlet.py -p ${nextport}"
-  if ! lk_get_result client-exec ; then
+  if ! get_katcp_reply client-exec ; then
     echo "!instrument-activate fail"
     return 1
   fi
@@ -708,7 +768,7 @@ function instrument_activate()
   sleep 2
 
   echo "?client-connect localhost:${nextport} ${subarray}"
-  if ! lk_get_result client-connect ; then
+  if ! get_katcp_reply client-connect ; then
     echo "!instrument-activate fail"
     # TODO: kill the corr instance to release resources
     return 1
@@ -729,7 +789,7 @@ function instrument_activate()
   fi
 
   echo "?client-rename corr localhost:${nextport}" 
-  if ! lk_get_result client-rename ; then
+  if ! get_katcp_reply client-rename ; then
     # TODO: kill the corr instance to release resources
     echo "!instrument-activate fail"
     return 1
@@ -737,7 +797,7 @@ function instrument_activate()
 
   if [ -n "${dmc_address}" ] ; then
     echo "?client-exec dmc-${subarray}-${instrument} ${subarray} kcpmpx -r -l dmc "${dmc_address}" -k -l cmc - -m -e cmc-dmc"
-    if ! lk_get_result client-exec ; then
+    if ! get_katcp_reply client-exec ; then
       kcpmsg -l warn "unable to launch dmc synchronisation helper"
     fi
   else
