Mockup instrument list

diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -604,10 +604,29 @@ function group_destroyed()
 
 function instrument_list()
 {
+  local instruments instrument
+
   if ! setup_instruments ; then
     echo "!instrument-list fail"
     return 1
   fi
+
+  push_failure
+
+  if [ -n "$1" ] ; then
+    fetch_var "instrument-size:$1"
+  else
+    fetch_var "instrument-size"
+  fi
+
+  if ! pop_failure  ; then
+    kcpmsg -l error "unable to retrieve instrument descriptiors"
+    echo "!instrument-list fail"
+  fi
+
+  for instrument in "${!var_result[@]}" ; do
+    echo "#instrument-list ${instrument} sufficient ${var_result[${instrument}]}"
+  done
 
   echo "!instrument-list ok"
 }
