More hacking

diff --git a/cmc/cmc-primary b/cmc/cmc-primary
--- a/cmc/cmc-primary
+++ b/cmc/cmc-primary
@@ -146,14 +146,7 @@ function array_assign()
 
   shift
 
-  unset t
-
-  while [ -n "$1" ] ; do
-    t=${t}${t:+-}${1}
-    shift
-  done
-
-  echo "?group-create $key"
+  echo "?group-create $key setup"
   if ! lk_get_result group-create ; then
     echo "!array-assign fail"
     return
@@ -166,7 +159,19 @@ function array_assign()
     return
   fi
 
-#  kcpmsg "have ${resources_up[*]} boards left to give"
+  echo "?client-exec subordinate ${key} ${NAME}-subordinate $*"
+  if ! lk_get_result client-exec ; then
+    echo "?group-halt ${key}"
+    echo "!array-assign fail"
+    return
+  fi
+
+  unset t
+
+  while [ -n "$1" ] ; do
+    t=${t}${t:+-}${1}
+    shift
+  done
 
   subarray_list[$key]=$t
 
